name: Build

on:
  push:
    branches:
      - 'feat/server-and-ci'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'

      - run: go build -o cofin-api ./main.go

      - run: docker build -t cofin-api .