name: Build

on:
  push:
    branches:
      - 'feat/server-and-ci'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'

      - run: go build -o cofin-api ./main.go

      - run: heroku login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - run: heroku container:login

      - run: heroku container:push web -a cofin-api

#      - run: heroku container:release web -a cofin-api
